List<Map> codes = [
  {
    "name": "افغانستان",
    "code": "AF",
    "dial_code": "+93",
    'time_zone': 'AFT',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Åland",
    "code": "AX",
    "dial_code": "+358",
    'time_zone': 'EET',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Shqipëria",
    "code": "AL",
    "dial_code": "+355",
    'time_zone': 'CET',
    'mask': '',
    'tz': '',
  },
  {
    "name": "الجزائر",
    "code": "DZ",
    "dial_code": "+213",
    'time_zone': 'CET',
    'mask': '',
    'tz': '',
  },
  {
    "name": "American Samoa",
    "code": "AS",
    "dial_code": "+1684",
    'time_zone': 'SST',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Andorra",
    "code": "AD",
    "dial_code": "+376",
    'time_zone': 'CET',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Angola",
    "code": "AO",
    "dial_code": "+244",
    'time_zone': 'WAT',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Anguilla",
    "code": "AI",
    "dial_code": "+1264",
    'time_zone': 'AST',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Antarctica",
    "code": "AQ",
    "dial_code": "+672",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Antigua and Barbuda",
    "code": "AG",
    "dial_code": "+1268",
    'time_zone': 'AST',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Argentina",
    "code": "AR",
    "dial_code": "+54",
    'time_zone': 'ART',
    'mask': '00-0000-0000',
    'tz': 'America',
  },
  {
    "name": "Հայաստան",
    "code": "AM",
    "dial_code": "+374",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Aruba",
    "code": "AW",
    "dial_code": "+297",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Australia",
    "code": "AU",
    "dial_code": "+61",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Österreich",
    "code": "AT",
    "dial_code": "+43",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Azərbaycan",
    "code": "AZ",
    "dial_code": "+994",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Bahamas",
    "code": "BS",
    "dial_code": "+1242",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "‏البحرين",
    "code": "BH",
    "dial_code": "+973",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Bangladesh",
    "code": "BD",
    "dial_code": "+880",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Barbados",
    "code": "BB",
    "dial_code": "+1246",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Белару́сь",
    "code": "BY",
    "dial_code": "+375",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "België",
    "code": "BE",
    "dial_code": "+32",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Belize",
    "code": "BZ",
    "dial_code": "+501",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Bénin",
    "code": "BJ",
    "dial_code": "+229",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Bermuda",
    "code": "BM",
    "dial_code": "+1441",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "ʼbrug-yul",
    "code": "BT",
    "dial_code": "+975",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Bolivia",
    "code": "BO",
    "dial_code": "+591",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Bosna i Hercegovina",
    "code": "BA",
    "dial_code": "+387",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Botswana",
    "code": "BW",
    "dial_code": "+267",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Bouvetøya",
    "code": "BV",
    "dial_code": "+47",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Brasil",
    "code": "BR",
    "dial_code": "+55",
    'time_zone': 'BRT',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "British Indian Ocean Territory",
    "code": "IO",
    "dial_code": "+246",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Negara Brunei Darussalam",
    "code": "BN",
    "dial_code": "+673",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "България",
    "code": "BG",
    "dial_code": "+359",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Burkina Faso",
    "code": "BF",
    "dial_code": "+226",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Burundi",
    "code": "BI",
    "dial_code": "+257",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Kâmpŭchéa",
    "code": "KH",
    "dial_code": "+855",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Cameroon",
    "code": "CM",
    "dial_code": "+237",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Canada",
    "code": "CA",
    "dial_code": "+1",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Cabo Verde",
    "code": "CV",
    "dial_code": "+238",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Cayman Islands",
    "code": "KY",
    "dial_code": "+ 345",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Ködörösêse tî Bêafrîka",
    "code": "CF",
    "dial_code": "+236",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Tchad",
    "code": "TD",
    "dial_code": "+235",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Chile",
    "code": "CL",
    "dial_code": "+56",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "中国",
    "code": "CN",
    "dial_code": "+86",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Christmas Island",
    "code": "CX",
    "dial_code": "+61",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Cocos (Keeling) Islands",
    "code": "CC",
    "dial_code": "+61",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Colombia",
    "code": "CO",
    "dial_code": "+57",
    'time_zone': 'COT',
    'mask': '000-000-0000',
    'tz': 'America',
  },
  {
    "name": "Komori",
    "code": "KM",
    "dial_code": "+269",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "République du Congo",
    "code": "CG",
    "dial_code": "+242",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "République démocratique du Congo",
    "code": "CD",
    "dial_code": "+243",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Cook Islands",
    "code": "CK",
    "dial_code": "+682",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Costa Rica",
    "code": "CR",
    "dial_code": "+506",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Côte d'Ivoire",
    "code": "CI",
    "dial_code": "+225",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Hrvatska",
    "code": "HR",
    "dial_code": "+385",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Cuba",
    "code": "CU",
    "dial_code": "+53",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Κύπρος",
    "code": "CY",
    "dial_code": "+357",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Česká republika",
    "code": "CZ",
    "dial_code": "+420",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Danmark",
    "code": "DK",
    "dial_code": "+45",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Djibouti",
    "code": "DJ",
    "dial_code": "+253",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Dominica",
    "code": "DM",
    "dial_code": "+1767",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "República Dominicana",
    "code": "DO",
    "dial_code": "+1849",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Ecuador",
    "code": "EC",
    "dial_code": "+593",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "مصر‎",
    "code": "EG",
    "dial_code": "+20",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "El Salvador",
    "code": "SV",
    "dial_code": "+503",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Guinea Ecuatorial",
    "code": "GQ",
    "dial_code": "+240",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "ኤርትራ",
    "code": "ER",
    "dial_code": "+291",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Eesti",
    "code": "EE",
    "dial_code": "+372",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "ኢትዮጵያ",
    "code": "ET",
    "dial_code": "+251",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Falkland Islands",
    "code": "FK",
    "dial_code": "+500",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Føroyar",
    "code": "FO",
    "dial_code": "+298",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Fiji",
    "code": "FJ",
    "dial_code": "+679",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Suomi",
    "code": "FI",
    "dial_code": "+358",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "France",
    "code": "FR",
    "dial_code": "+33",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guyane française",
    "code": "GF",
    "dial_code": "+594",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Polynésie française",
    "code": "PF",
    "dial_code": "+689",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Territoire des Terres australes et antarctiques fr",
    "code": "TF",
    "dial_code": "+262",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Gabon",
    "code": "GA",
    "dial_code": "+241",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Gambia",
    "code": "GM",
    "dial_code": "+220",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "საქართველო",
    "code": "GE",
    "dial_code": "+995",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Deutschland",
    "code": "DE",
    "dial_code": "+49",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Ghana",
    "code": "GH",
    "dial_code": "+233",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Gibraltar",
    "code": "GI",
    "dial_code": "+350",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Ελλάδα",
    "code": "GR",
    "dial_code": "+30",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Kalaallit Nunaat",
    "code": "GL",
    "dial_code": "+299",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Grenada",
    "code": "GD",
    "dial_code": "+1473",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guadeloupe",
    "code": "GP",
    "dial_code": "+590",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guam",
    "code": "GU",
    "dial_code": "+1671",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guatemala",
    "code": "GT",
    "dial_code": "+502",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Guernsey",
    "code": "GG",
    "dial_code": "+44",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guinée",
    "code": "GN",
    "dial_code": "+224",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guiné-Bissau",
    "code": "GW",
    "dial_code": "+245",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Guyana",
    "code": "GY",
    "dial_code": "+592",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Haïti",
    "code": "HT",
    "dial_code": "+509",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Heard Island and McDonald Islands",
    "code": "HM",
    "dial_code": "+0",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Vaticano",
    "code": "VA",
    "dial_code": "+379",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Honduras",
    "code": "HN",
    "dial_code": "+504",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "香港",
    "code": "HK",
    "dial_code": "+852",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Magyarország",
    "code": "HU",
    "dial_code": "+36",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Ísland",
    "code": "IS",
    "dial_code": "+354",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "भारत",
    "code": "IN",
    "dial_code": "+91",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Indonesia",
    "code": "ID",
    "dial_code": "+62",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "ایران",
    "code": "IR",
    "dial_code": "+98",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "العراق",
    "code": "IQ",
    "dial_code": "+964",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Éire",
    "code": "IE",
    "dial_code": "+353",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Isle of Man",
    "code": "IM",
    "dial_code": "+44",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "יִשְׂרָאֵל",
    "code": "IL",
    "dial_code": "+972",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Italia",
    "code": "IT",
    "dial_code": "+39",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Jamaica",
    "code": "JM",
    "dial_code": "+1876",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "日本",
    "code": "JP",
    "dial_code": "+81",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Jersey",
    "code": "JE",
    "dial_code": "+44",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "الأردن",
    "code": "JO",
    "dial_code": "+962",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Қазақстан",
    "code": "KZ",
    "dial_code": "+7",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Kenya",
    "code": "KE",
    "dial_code": "+254",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Kiribati",
    "code": "KI",
    "dial_code": "+686",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "북한",
    "code": "KP",
    "dial_code": "+850",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "대한민국",
    "code": "KR",
    "dial_code": "+82",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Republika e Kosovës",
    "code": "XK",
    "dial_code": "+383",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "الكويت",
    "code": "KW",
    "dial_code": "+965",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Кыргызстан",
    "code": "KG",
    "dial_code": "+996",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "ສປ��ລາວ",
    "code": "LA",
    "dial_code": "+856",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Latvija",
    "code": "LV",
    "dial_code": "+371",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "لبنان",
    "code": "LB",
    "dial_code": "+961",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Lesotho",
    "code": "LS",
    "dial_code": "+266",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Liberia",
    "code": "LR",
    "dial_code": "+231",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "‏ليبيا",
    "code": "LY",
    "dial_code": "+218",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Liechtenstein",
    "code": "LI",
    "dial_code": "+423",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Lietuva",
    "code": "LT",
    "dial_code": "+370",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Luxembourg",
    "code": "LU",
    "dial_code": "+352",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "澳門",
    "code": "MO",
    "dial_code": "+853",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Македонија",
    "code": "MK",
    "dial_code": "+389",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Madagasikara",
    "code": "MG",
    "dial_code": "+261",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Malawi",
    "code": "MW",
    "dial_code": "+265",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Malaysia",
    "code": "MY",
    "dial_code": "+60",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Maldives",
    "code": "MV",
    "dial_code": "+960",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Mali",
    "code": "ML",
    "dial_code": "+223",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Malta",
    "code": "MT",
    "dial_code": "+356",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "M̧ajeļ",
    "code": "MH",
    "dial_code": "+692",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Martinique",
    "code": "MQ",
    "dial_code": "+596",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "موريتانيا",
    "code": "MR",
    "dial_code": "+222",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Maurice",
    "code": "MU",
    "dial_code": "+230",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Mayotte",
    "code": "YT",
    "dial_code": "+262",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "México",
    "code": "MX",
    "dial_code": "+52",
    'time_zone': 'CST',
    'mask': '00-0000-0000',
    'tz': 'America',
  },
  {
    "name": "Micronesia",
    "code": "FM",
    "dial_code": "+691",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Moldova",
    "code": "MD",
    "dial_code": "+373",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Monaco",
    "code": "MC",
    "dial_code": "+377",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Монгол улс",
    "code": "MN",
    "dial_code": "+976",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Црна Гора",
    "code": "ME",
    "dial_code": "+382",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Montserrat",
    "code": "MS",
    "dial_code": "+1664",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "المغرب",
    "code": "MA",
    "dial_code": "+212",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Moçambique",
    "code": "MZ",
    "dial_code": "+258",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Myanma",
    "code": "MM",
    "dial_code": "+95",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Namibia",
    "code": "NA",
    "dial_code": "+264",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Nauru",
    "code": "NR",
    "dial_code": "+674",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "नपल",
    "code": "NP",
    "dial_code": "+977",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Nederland",
    "code": "NL",
    "dial_code": "+31",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Netherlands Antilles",
    "code": "AN",
    "dial_code": "+599",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Nouvelle-Calédonie",
    "code": "NC",
    "dial_code": "+687",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "New Zealand",
    "code": "NZ",
    "dial_code": "+64",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Nicaragua",
    "code": "NI",
    "dial_code": "+505",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Niger",
    "code": "NE",
    "dial_code": "+227",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Nigeria",
    "code": "NG",
    "dial_code": "+234",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Niuē",
    "code": "NU",
    "dial_code": "+683",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Norfolk Island",
    "code": "NF",
    "dial_code": "+672",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Northern Mariana Islands",
    "code": "MP",
    "dial_code": "+1670",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Norge",
    "code": "NO",
    "dial_code": "+47",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "عمان",
    "code": "OM",
    "dial_code": "+968",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Pakistan",
    "code": "PK",
    "dial_code": "+92",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Palau",
    "code": "PW",
    "dial_code": "+680",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "فلسطين",
    "code": "PS",
    "dial_code": "+970",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Panamá",
    "code": "PA",
    "dial_code": "+507",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Papua Niugini",
    "code": "PG",
    "dial_code": "+675",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Paraguay",
    "code": "PY",
    "dial_code": "+595",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Perú",
    "code": "PE",
    "dial_code": "+51",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Pilipinas",
    "code": "PH",
    "dial_code": "+63",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Pitcairn Islands",
    "code": "PN",
    "dial_code": "+64",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Polska",
    "code": "PL",
    "dial_code": "+48",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Portugal",
    "code": "PT",
    "dial_code": "+351",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Puerto Rico",
    "code": "PR",
    "dial_code": "+1939",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "قطر",
    "code": "QA",
    "dial_code": "+974",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "România",
    "code": "RO",
    "dial_code": "+40",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "��оссия",
    "code": "RU",
    "dial_code": "+7",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Rwanda",
    "code": "RW",
    "dial_code": "+250",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "La Réunion",
    "code": "RE",
    "dial_code": "+262",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint-Barthélemy",
    "code": "BL",
    "dial_code": "+590",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint Helena",
    "code": "SH",
    "dial_code": "+290",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint Kitts and Nevis",
    "code": "KN",
    "dial_code": "+1869",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint Lucia",
    "code": "LC",
    "dial_code": "+1758",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint-Martin",
    "code": "MF",
    "dial_code": "+590",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint-Pierre-et-Miquelon",
    "code": "PM",
    "dial_code": "+508",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "code": "VC",
    "dial_code": "+1784",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Samoa",
    "code": "WS",
    "dial_code": "+685",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "San Marino",
    "code": "SM",
    "dial_code": "+378",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "São Tomé e Príncipe",
    "code": "ST",
    "dial_code": "+239",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "العربية السعودية",
    "code": "SA",
    "dial_code": "+966",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Sénégal",
    "code": "SN",
    "dial_code": "+221",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Србија",
    "code": "RS",
    "dial_code": "+381",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Seychelles",
    "code": "SC",
    "dial_code": "+248",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Sierra Leone",
    "code": "SL",
    "dial_code": "+232",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Singapore",
    "code": "SG",
    "dial_code": "+65",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Slovensko",
    "code": "SK",
    "dial_code": "+421",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Slovenija",
    "code": "SI",
    "dial_code": "+386",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Solomon Islands",
    "code": "SB",
    "dial_code": "+677",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Soomaaliya",
    "code": "SO",
    "dial_code": "+252",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "South Africa",
    "code": "ZA",
    "dial_code": "+27",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "South Sudan",
    "code": "SS",
    "dial_code": "+211",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "South Georgia",
    "code": "GS",
    "dial_code": "+500",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "España",
    "code": "ES",
    "dial_code": "+34",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "śrī laṃkāva",
    "code": "LK",
    "dial_code": "+94",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "السودان",
    "code": "SD",
    "dial_code": "+249",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Suriname",
    "code": "SR",
    "dial_code": "+597",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Svalbard og Jan Mayen",
    "code": "SJ",
    "dial_code": "+47",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Swaziland",
    "code": "SZ",
    "dial_code": "+268",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Sverige",
    "code": "SE",
    "dial_code": "+46",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Schweiz",
    "code": "CH",
    "dial_code": "+41",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "سوريا",
    "code": "SY",
    "dial_code": "+963",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "臺灣",
    "code": "TW",
    "dial_code": "+886",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Тоҷикистон",
    "code": "TJ",
    "dial_code": "+992",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Tanzania",
    "code": "TZ",
    "dial_code": "+255",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "ประเทศไทย",
    "code": "TH",
    "dial_code": "+66",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Timor-Leste",
    "code": "TL",
    "dial_code": "+670",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Togo",
    "code": "TG",
    "dial_code": "+228",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Tokelau",
    "code": "TK",
    "dial_code": "+690",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Tonga",
    "code": "TO",
    "dial_code": "+676",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Trinidad and Tobago",
    "code": "TT",
    "dial_code": "+1868",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "تونس",
    "code": "TN",
    "dial_code": "+216",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Türkiye",
    "code": "TR",
    "dial_code": "+90",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Türkmenistan",
    "code": "TM",
    "dial_code": "+993",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Turks and Caicos Islands",
    "code": "TC",
    "dial_code": "+1649",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Tuvalu",
    "code": "TV",
    "dial_code": "+688",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Uganda",
    "code": "UG",
    "dial_code": "+256",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Україна",
    "code": "UA",
    "dial_code": "+380",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "دولة الإمارات العربية المتحدة",
    "code": "AE",
    "dial_code": "+971",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "United Kingdom",
    "code": "GB",
    "dial_code": "+44",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "United States",
    "code": "US",
    "dial_code": "+1",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Uruguay",
    "code": "UY",
    "dial_code": "+598",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "O‘zbekiston",
    "code": "UZ",
    "dial_code": "+998",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Vanuatu",
    "code": "VU",
    "dial_code": "+678",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Venezuela",
    "code": "VE",
    "dial_code": "+58",
    'time_zone': '',
    'mask': '',
    'tz': 'America',
  },
  {
    "name": "Việt Nam",
    "code": "VN",
    "dial_code": "+84",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "British Virgin Islands",
    "code": "VG",
    "dial_code": "+1284",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "United States Virgin Islands",
    "code": "VI",
    "dial_code": "+1340",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Wallis et Futuna",
    "code": "WF",
    "dial_code": "+681",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "اليَمَن",
    "code": "YE",
    "dial_code": "+967",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Zambia",
    "code": "ZM",
    "dial_code": "+260",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
  {
    "name": "Zimbabwe",
    "code": "ZW",
    "dial_code": "+263",
    'time_zone': '',
    'mask': '',
    'tz': '',
  },
];
